spring:
  application:
    name: transakt
  datasource:
    url: jdbc:postgresql://localhost:5432/transakt
    username: aman
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true